# ./prometheus/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hasura'
    static_configs:
      - targets: ['graphql-engine:8080']

  - job_name: 'event-broker'
    static_configs:
      - targets: ['event-broker:4000']

  - job_name: 'email-service'
    static_configs:
      - targets: ['email-service:8000']