version: '3'

services:
  db:
    image: postgres:13
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    env_file: ./backend/.env
    environment:
       - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    depends_on:
      - db
    restart: always 

volumes:
  postgres_data: 