name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FRONTEND_URL: http://localhost:5173
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Create env file
      run: |
        echo "SECRET_KEY=${SECRET_KEY}" > backend/.env
        echo "FRONTEND_URL=${FRONTEND_URL}" >> backend/.env
        echo "EMAIL_HOST_USER=${EMAIL_HOST_USER}" >> backend/.env
        echo "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}" >> backend/.env
    
    - name: Build and start containers
      run: |
        docker-compose build
        docker-compose up -d
    
    - name: Run Tests
      run: |
        docker-compose exec -T backend pytest
    
    - name: Check Logs
      if: always()
      run: docker-compose logs
    
    - name: Clean up
      if: always()
      run: docker-compose down 